import json
import asyncio
from typing import List, Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from bridge import bridge, flatten_chat_prompt_and_files, decode_image_to_file

router = APIRouter()

# Ollama Compatibility Endpoints
SIGNED_IN_INPUT_CONTEXT_LENGTH = 1_000_000
SIGNED_OUT_INPUT_CONTEXT_LENGTH = 32_768
OUTPUT_CONTEXT_LENGTH = 8_192

def get_model_entry(input_context_length: int) -> dict:
    return {
        "name": "gemini-proxy",
        "model": "gemini-proxy",
        "modified_at": "2026-03-13T00:00:00.000000000Z",
        "size": 1,
        "digest": "3f3afba5eec3eced16458929f3700a4f2aa134e7771a32339f6efd8006f2b593",
        "details": {
            "format": "gguf",
            "family": "gemini",
            "families": ["gemini"],
            "parameter_size": "20000B",
            "quantization_level": "Q4_0",
        }
    }

def get_running_model_entry(input_context_length: int) -> dict:
    tag = get_model_entry(input_context_length)
    return {
        "name": tag["name"],
        "model": tag["model"],
        "size": tag["size"],
        "digest": tag["digest"],
        "details": {
            "parent_model": "",
            "format": tag["details"]["format"],
            "family": tag["details"]["family"],
            "families": tag["details"]["families"],
            "parameter_size": tag["details"]["parameter_size"],
            "quantization_level": tag["details"]["quantization_level"],
        },
        "expires_at": "2099-12-31T23:59:59Z",
        "size_vram": tag["size"]
    }

def get_model_info(input_context_length: int) -> dict:
    return {
        "general.architecture": "gemini",
        "general.file_type": 2,
        "general.parameter_count": 20000e9,
        "general.quantization_version": 2,
        "llama.attention.head_count": 32,
        "llama.attention.head_count_kv": 8,
        "llama.attention.layer_norm_rms_epsilon": 0.00001,
        "llama.block_count": 32,
        "llama.context_length": input_context_length,
        "llama.output_context_length": OUTPUT_CONTEXT_LENGTH,
        "llama.embedding_length": 4096,
        "llama.feed_forward_length": 14336,
        "llama.rope.dimension_count": 128,
        "llama.rope.freq_base": 500000,
        "llama.vocab_size": 128256,
        "tokenizer.ggml.bos_token_id": 128000,
        "tokenizer.ggml.eos_token_id": 128009,
        "tokenizer.ggml.merges": [],
        "tokenizer.ggml.model": "gpt2",
        "tokenizer.ggml.pre": "llama-bpe",
        "tokenizer.ggml.token_type": [],
        "tokenizer.ggml.tokens": []
    }

def context_length_for_sign_in(sign_in_present: Optional[bool]) -> int:
    if sign_in_present is False:
        return SIGNED_IN_INPUT_CONTEXT_LENGTH
    return SIGNED_OUT_INPUT_CONTEXT_LENGTH

@router.get("/api/tags")
async def tags():
    sign_in_present = await bridge.request_gemini_sign_in_presence()
    input_context_length = context_length_for_sign_in(sign_in_present)
    return {"models": [get_model_entry(input_context_length)]}

@router.get("/api/ps")
async def running_models():
    sign_in_present = await bridge.request_gemini_sign_in_presence()
    input_context_length = context_length_for_sign_in(sign_in_present)
    return {"models": [get_running_model_entry(input_context_length)]}

@router.post("/api/show")
async def show_model(req: dict):
    model = req.get("model")
    sign_in_present = await bridge.request_gemini_sign_in_presence()
    input_context_length = context_length_for_sign_in(sign_in_present)
    entry = get_model_entry(input_context_length)
    if model != entry["model"] and model != entry["name"]:
        raise HTTPException(status_code=404, detail="model not found")
        
    return {
        "modelfile": f"# Modelfile generated by gemini-proxy\nFROM {entry['model']}\n",
        "parameters": f"num_ctx {input_context_length}\nnum_predict {OUTPUT_CONTEXT_LENGTH}\n",
        "template": "{{ .Prompt }}",
        "details": entry["details"],
        "capabilities": ["completion", "chat", "vision", "tools", "thinking"],
        "model_info": get_model_info(input_context_length)
    }

@router.get("/api/version")
async def version():
    return {"version": "0.17.1"}

# Stubs
@router.post("/api/copy")
async def copy_model(req: dict):
    raise HTTPException(status_code=400, detail="unsupported")

@router.delete("/api/delete")
async def delete_model(req: dict):
    raise HTTPException(status_code=400, detail="unsupported")

@router.post("/api/embed")
async def embed_model(req: dict):
    raise HTTPException(status_code=400, detail="unsupported")

@router.post("/api/pull")
async def pull_model(req: dict):
    raise HTTPException(status_code=400, detail="unsupported")

@router.post("/api/push")
async def push_model(req: dict):
    raise HTTPException(status_code=400, detail="unsupported")

# Ollama Generate & Chat
def validate_generate_request(req: dict):
    if "suffix" in req:
        raise HTTPException(status_code=400, detail="the `suffix` field is not supported")
    if "format" in req:
        fmt = req["format"]
        if fmt != "json":
            raise HTTPException(status_code=400, detail="the `format` field only supports the string `json`")
    if "raw" in req:
        raise HTTPException(status_code=400, detail="the `raw` field is not supported")
    if "logprobs" in req or "top_logprobs" in req:
        raise HTTPException(status_code=400, detail="the `logprobs` and `top_logprobs` fields are not supported")

def format_prompt(system: Optional[str], prompt: str) -> str:
    if not prompt.strip():
        return prompt
    if not system or not system.strip():
        return prompt
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": prompt}
    ]
    return json.dumps(messages)

@router.post("/api/generate")
async def generate(req: dict):
    validate_generate_request(req)
    model = req.get("model", "gemini-proxy")
    prompt = format_prompt(req.get("system"), req.get("prompt", ""))
    images = req.get("images") or []
    files = [decode_image_to_file(img) for img in images]
    stream_enabled = req.get("stream", True)
    created_at = "2026-03-13T00:00:00.000000000Z"
    
    if not bridge.active_websocket:
        raise HTTPException(status_code=503, detail="No browser extension connected")
        
    if not model.startswith("gemini") and model != "gemini-proxy":
        if stream_enabled:
            async def unsupported_stream():
                yield json.dumps({
                    "model": model,
                    "created_at": created_at,
                    "response": "Unsupported model",
                    "done": True
                }) + "\n"
            return StreamingResponse(unsupported_stream(), media_type="application/x-ndjson")
        else:
            return {
                "model": model,
                "created_at": created_at,
                "response": "Unsupported model",
                "done": True,
                "done_reason": "stop",
                "total_duration": 0,
                "load_duration": 0,
                "prompt_eval_count": 0,
                "prompt_eval_duration": 0,
                "eval_count": 0,
                "eval_duration": 0,
            }
            
    cmd_id = await bridge.get_next_id()
    queue = asyncio.Queue()
    bridge.register_receiver(cmd_id, queue)
    
    try:
        await bridge.send_command(cmd_id, "gemini-generate", prompt=prompt, files=files)
    except Exception as e:
        bridge.unregister_receiver(cmd_id)
        raise HTTPException(status_code=500, detail=f"Failed to send command: {e}")
        
    if stream_enabled:
        async def ollama_generate_stream():
            try:
                while True:
                    try:
                        item = await asyncio.wait_for(queue.get(), timeout=1200.0)
                    except asyncio.TimeoutError:
                        yield json.dumps({
                            "model": model,
                            "created_at": created_at,
                            "response": "",
                            "done": True,
                            "error": "Timeout waiting for response from browser extension"
                        }) + "\n"
                        break
                        
                    error = item.get("error")
                    if error:
                        yield json.dumps({
                            "model": model,
                            "created_at": created_at,
                            "response": "",
                            "done": True,
                            "error": error
                        }) + "\n"
                        break
                        
                    text = item.get("text", "")
                    done = item.get("done", False)
                    
                    yield json.dumps({
                        "model": model,
                        "created_at": created_at,
                        "response": text,
                        "done": done
                    }) + "\n"
                    
                    if done:
                        break
            finally:
                bridge.unregister_receiver(cmd_id)
        return StreamingResponse(ollama_generate_stream(), media_type="application/x-ndjson")
    else:
        accumulated_text = []
        try:
            while True:
                try:
                    item = await asyncio.wait_for(queue.get(), timeout=1200.0)
                except asyncio.TimeoutError:
                    raise HTTPException(status_code=504, detail="Timeout waiting for browser response")
                error = item.get("error")
                if error:
                    raise HTTPException(status_code=500, detail=error)
                text = item.get("text", "")
                if text:
                    accumulated_text.append(text)
                if item.get("done", False):
                    break
        finally:
            bridge.unregister_receiver(cmd_id)
            
        full_text = "".join(accumulated_text)
        return {
            "model": model,
            "created_at": created_at,
            "response": full_text,
            "done": True,
            "done_reason": "stop",
            "total_duration": 0,
            "load_duration": 0,
            "prompt_eval_count": 0,
            "prompt_eval_duration": 0,
            "eval_count": 0,
            "eval_duration": 0,
        }

def validate_chat_request(req: dict):
    if "format" in req:
        fmt = req["format"]
        if fmt != "json":
            raise HTTPException(status_code=400, detail="the `format` field only supports the string `json`")

@router.post("/api/chat")
async def chat(req: dict):
    validate_chat_request(req)
    model = req.get("model", "gemini-proxy")
    messages = req.get("messages") or []
    prompt, files = flatten_chat_prompt_and_files(messages)
    stream_enabled = req.get("stream", True)
    created_at = "2026-03-13T00:00:00.000000000Z"
    
    if not bridge.active_websocket:
        raise HTTPException(status_code=503, detail="No browser extension connected")
        
    if not model.startswith("gemini") and model != "gemini-proxy":
        if stream_enabled:
            async def unsupported_stream():
                yield json.dumps({
                    "model": model,
                    "created_at": created_at,
                    "message": {
                        "role": "assistant",
                        "content": "Unsupported model"
                    },
                    "done": True
                }) + "\n"
            return StreamingResponse(unsupported_stream(), media_type="application/x-ndjson")
        else:
            return {
                "model": model,
                "created_at": created_at,
                "message": {
                    "role": "assistant",
                    "content": "Unsupported model"
                },
                "done": True,
                "total_duration": 0,
                "load_duration": 0,
                "prompt_eval_count": 0,
                "prompt_eval_duration": 0,
                "eval_count": 0,
                "eval_duration": 0,
            }
            
    cmd_id = await bridge.get_next_id()
    queue = asyncio.Queue()
    bridge.register_receiver(cmd_id, queue)
    
    try:
        await bridge.send_command(cmd_id, "gemini-generate", prompt=prompt, files=files)
    except Exception as e:
        bridge.unregister_receiver(cmd_id)
        raise HTTPException(status_code=500, detail=f"Failed to send command: {e}")
        
    if stream_enabled:
        async def ollama_chat_stream():
            try:
                while True:
                    try:
                        item = await asyncio.wait_for(queue.get(), timeout=1200.0)
                    except asyncio.TimeoutError:
                        yield json.dumps({
                            "model": model,
                            "created_at": created_at,
                            "message": {
                                "role": "assistant",
                                "content": ""
                            },
                            "done": True,
                            "error": "Timeout waiting for response from browser extension"
                        }) + "\n"
                        break
                        
                    error = item.get("error")
                    if error:
                        yield json.dumps({
                            "model": model,
                            "created_at": created_at,
                            "message": {
                                "role": "assistant",
                                "content": ""
                            },
                            "done": True,
                            "error": error
                        }) + "\n"
                        break
                        
                    text = item.get("text", "")
                    done = item.get("done", False)
                    
                    yield json.dumps({
                        "model": model,
                        "created_at": created_at,
                        "message": {
                            "role": "assistant",
                            "content": text
                        },
                        "done": done
                    }) + "\n"
                    
                    if done:
                        break
            finally:
                bridge.unregister_receiver(cmd_id)
        return StreamingResponse(ollama_chat_stream(), media_type="application/x-ndjson")
    else:
        accumulated_text = []
        try:
            while True:
                try:
                    item = await asyncio.wait_for(queue.get(), timeout=1200.0)
                except asyncio.TimeoutError:
                    raise HTTPException(status_code=504, detail="Timeout waiting for browser response")
                error = item.get("error")
                if error:
                    raise HTTPException(status_code=500, detail=error)
                text = item.get("text", "")
                if text:
                    accumulated_text.append(text)
                if item.get("done", False):
                    break
        finally:
            bridge.unregister_receiver(cmd_id)
            
        full_text = "".join(accumulated_text)
        return {
            "model": model,
            "created_at": created_at,
            "message": {
                "role": "assistant",
                "content": full_text
            },
            "done": True,
            "total_duration": 0,
            "load_duration": 0,
            "prompt_eval_count": 0,
            "prompt_eval_duration": 0,
            "eval_count": 0,
            "eval_duration": 0,
        }
