use rocket::get;
use rocket::post;
use rocket::serde::json::Json;
use rocket::State;
use serde::Deserialize;
use serde::Serialize;

use crate::api_tags::{ExtensionBridge, request_gemini_sign_in_presence};
use crate::error::AppResult;

#[derive(Debug, Clone, Serialize)]
pub struct TagsResponse {
    models: Vec<ModelEntry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ModelEntry {
    name: String,
    model: String,
    modified_at: String,
    size: u64,
    digest: String,
    details: ModelDetails,
}

#[derive(Debug, Clone, Serialize)]
pub struct ModelDetails {
    format: String,
    family: String,
    families: Vec<String>,
    parameter_size: String,
    quantization_level: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct PsResponse {
    models: Vec<RunningModelEntry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct RunningModelEntry {
    name: String,
    model: String,
    size: u64,
    digest: String,
    details: RunningModelDetails,
    expires_at: String,
    size_vram: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct RunningModelDetails {
    parent_model: String,
    format: String,
    family: String,
    families: Vec<String>,
    parameter_size: String,
    quantization_level: String,
}

#[derive(Debug, Deserialize)]
pub struct ShowRequest {
    model: String,
    #[serde(default)]
    verbose: Option<bool>,
}

#[derive(Debug, Serialize)]
pub struct ShowResponse {
    modelfile: String,
    parameters: String,
    template: String,
    details: ModelDetails,
    model_info: serde_json::Value,
}

#[derive(Debug, Clone)]
struct ModelCatalogEntry {
    tag: ModelEntry,
    modelfile: String,
    parameters: String,
    template: String,
    model_info: serde_json::Value,
}

impl ModelCatalogEntry {
    fn to_running_model(&self) -> RunningModelEntry {
        RunningModelEntry {
            name: self.tag.name.clone(),
            model: self.tag.model.clone(),
            size: self.tag.size,
            digest: self.tag.digest.clone(),
            details: RunningModelDetails {
                parent_model: "".to_string(),
                format: self.tag.details.format.clone(),
                family: self.tag.details.family.clone(),
                families: self.tag.details.families.clone(),
                parameter_size: self.tag.details.parameter_size.clone(),
                quantization_level: self.tag.details.quantization_level.clone(),
            },
            expires_at: "2099-12-31T23:59:59Z".to_string(),
            size_vram: self.tag.size,
        }
    }
}

fn gemini_catalog_entry() -> ModelCatalogEntry {
    ModelCatalogEntry {
        tag: ModelEntry {
            name: "gemini-proxy".to_string(),
            model: "gemini-proxy".to_string(),
            modified_at: "2026-03-13T00:00:00.000000000Z".to_string(),
            size: 1,
            digest: "3f3afba5eec3eced16458929f3700a4f2aa134e7771a32339f6efd8006f2b593".to_string(), // sha256("gemini-proxy")
            details: ModelDetails {
                format: "gguf".to_string(),
                family: "gemini".to_string(),
                families: vec!["gemini".to_string()],
                parameter_size: "20000B".to_string(),
                quantization_level: "N/A".to_string(),
            },
        },
        modelfile: "# Modelfile generated by gemini-ollama\nFROM gemini-proxy\n".to_string(),
        parameters: "".to_string(),
        template: "{{ .Prompt }}".to_string(),
        model_info: serde_json::json!({
            "general.architecture": "gemini",
            "general.parameter_count": 0,
            "general.quantization_version": 0,
        }),
    }
}

#[get("/api/tags")]
pub async fn tags(state: &State<ExtensionBridge>) -> Json<TagsResponse> {
    let sign_in_present = request_gemini_sign_in_presence(state).await.ok();
    let gemini_available = matches!(sign_in_present, Some(false));

    let mut models = Vec::new();
    if gemini_available {
        models.push(gemini_catalog_entry().tag);
    }

    Json(TagsResponse { models })
}

#[get("/api/ps")]
pub async fn running_models(state: &State<ExtensionBridge>) -> Json<PsResponse> {
    let sign_in_present = request_gemini_sign_in_presence(state).await.ok();
    let gemini_available = matches!(sign_in_present, Some(false));

    let mut models = Vec::new();
    if gemini_available {
        models.push(gemini_catalog_entry().to_running_model());
    }

    Json(PsResponse { models })
}

#[post("/api/show", format = "json", data = "<payload>")]
pub async fn show_model(payload: Json<ShowRequest>) -> AppResult<Json<ShowResponse>> {
    let req = payload.into_inner();
    let _verbose = req.verbose.unwrap_or(false);

    let entry = gemini_catalog_entry();
    if req.model != entry.tag.model && req.model != entry.tag.name {
        return Err(anyhow::anyhow!("model not found").into());
    }

    Ok(Json(ShowResponse {
        modelfile: entry.modelfile,
        parameters: entry.parameters,
        template: entry.template,
        details: entry.tag.details,
        model_info: entry.model_info,
    }))
}
