use rocket::get;
use rocket::post;
use rocket::serde::json::Json;
use rocket::State;
use serde::Deserialize;
use serde::Serialize;
use serde_json::Value;

use crate::extension_bridge::{ExtensionBridge, request_gemini_sign_in_presence};
use crate::error::AppResult;
use crate::app_bail as bail;

const SIGNED_IN_INPUT_CONTEXT_LENGTH: u64 = 1_000_000; // TODO that's for pro, it will need to be adjusted for regular accounts
const SIGNED_OUT_INPUT_CONTEXT_LENGTH: u64 = 32_768;
const OUTPUT_CONTEXT_LENGTH: u64 = 8_192;

#[derive(Debug, Clone, Serialize)]
pub struct TagsResponse {
    models: Vec<ModelEntry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ModelEntry {
    name: String,
    model: String,
    modified_at: String,
    size: u64,
    digest: String,
    details: ModelDetails,
}

#[derive(Debug, Clone, Serialize)]
pub struct ModelDetails {
    format: String,
    family: String,
    families: Vec<String>,
    parameter_size: String,
    quantization_level: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct PsResponse {
    models: Vec<RunningModelEntry>,
}

#[derive(Debug, Clone, Serialize)]
pub struct RunningModelEntry {
    name: String,
    model: String,
    size: u64,
    digest: String,
    details: RunningModelDetails,
    expires_at: String,
    size_vram: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct RunningModelDetails {
    parent_model: String,
    format: String,
    family: String,
    families: Vec<String>,
    parameter_size: String,
    quantization_level: String,
}

#[derive(Debug, Deserialize)]
pub struct ShowRequest {
    model: String,
    #[serde(default)]
    verbose: Option<bool>,
}

#[derive(Debug, Serialize)]
pub struct ShowResponse {
    modelfile: String,
    parameters: String,
    template: String,
    details: ModelDetails,
    capabilities: Vec<String>,
    model_info: Value,
}

#[derive(Debug, Clone)]
struct ModelCatalogEntry {
    tag: ModelEntry,
    modelfile: String,
    parameters: String,
    template: String,
    capabilities: Vec<String>,
    model_info: Value,
}

impl ModelCatalogEntry {
    fn to_running_model(&self) -> RunningModelEntry {
        RunningModelEntry {
            name: self.tag.name.clone(),
            model: self.tag.model.clone(),
            size: self.tag.size,
            digest: self.tag.digest.clone(),
            details: RunningModelDetails {
                parent_model: "".to_string(),
                format: self.tag.details.format.clone(),
                family: self.tag.details.family.clone(),
                families: self.tag.details.families.clone(),
                parameter_size: self.tag.details.parameter_size.clone(),
                quantization_level: self.tag.details.quantization_level.clone(),
            },
            expires_at: "2099-12-31T23:59:59Z".to_string(),
            size_vram: self.tag.size,
        }
    }
}

fn context_length_for_sign_in(sign_in_present: Option<bool>) -> u64 {
    if matches!(sign_in_present, Some(true)) {
        SIGNED_IN_INPUT_CONTEXT_LENGTH
    } else {
        SIGNED_OUT_INPUT_CONTEXT_LENGTH
    }
}

fn gemini_catalog_entry(input_context_length: u64) -> ModelCatalogEntry {
    ModelCatalogEntry {
        tag: ModelEntry {
            name: "gemini-proxy".to_string(),
            model: "gemini-proxy".to_string(),
            modified_at: "2026-03-13T00:00:00.000000000Z".to_string(),
            size: 1,
            digest: "3f3afba5eec3eced16458929f3700a4f2aa134e7771a32339f6efd8006f2b593".to_string(), // sha256("gemini-proxy")
            details: ModelDetails {
                format: "gguf".to_string(),
                family: "gemini".to_string(),
                families: vec!["gemini".to_string()],
                parameter_size: "20000B".to_string(),
                quantization_level: "Q4_0".to_string(),
            },
        },
        modelfile: "# Modelfile generated by gemini-proxy\nFROM gemini-proxy\n".to_string(),
        parameters: format!(
            "num_ctx {}\nnum_predict {}\n",
            input_context_length,
            OUTPUT_CONTEXT_LENGTH,
        ),
        template: "{{ .Prompt }}".to_string(),
        capabilities: vec![
            String::from("completion"),
            String::from("chat"),
            String::from("vision"),
            String::from("tools"),
            String::from("thinking")
        ],
        model_info: serde_json::json!({
            "general.architecture": "gemini",
            "general.file_type": 2,
            "general.parameter_count": 20000e9,
            "general.quantization_version": 2,
            "llama.attention.head_count": 32,
            "llama.attention.head_count_kv": 8,
            "llama.attention.layer_norm_rms_epsilon": 0.00001,
            "llama.block_count": 32,
            "llama.context_length": input_context_length,
            "llama.output_context_length": OUTPUT_CONTEXT_LENGTH,
            "llama.embedding_length": 4096,
            "llama.feed_forward_length": 14336,
            "llama.rope.dimension_count": 128,
            "llama.rope.freq_base": 500000,
            "llama.vocab_size": 128256,
            "tokenizer.ggml.bos_token_id": 128000,
            "tokenizer.ggml.eos_token_id": 128009,
            "tokenizer.ggml.merges": [],
            "tokenizer.ggml.model": "gpt2",
            "tokenizer.ggml.pre": "llama-bpe",
            "tokenizer.ggml.token_type": [],
            "tokenizer.ggml.tokens": []
        }),
    }
}

#[get("/api/tags")]
pub async fn tags(state: &State<ExtensionBridge>) -> Json<TagsResponse> {
    let sign_in_present = request_gemini_sign_in_presence(state).await.ok();
    let input_context_length = context_length_for_sign_in(sign_in_present);

    let models = vec![gemini_catalog_entry(input_context_length).tag];

    Json(TagsResponse { models })
}

#[get("/api/ps")]
pub async fn running_models(state: &State<ExtensionBridge>) -> Json<PsResponse> {
    let sign_in_present = request_gemini_sign_in_presence(state).await.ok();
    let input_context_length = context_length_for_sign_in(sign_in_present);

    let models = vec![gemini_catalog_entry(input_context_length).to_running_model()];

    Json(PsResponse { models })
}

#[post("/api/show", format = "json", data = "<payload>")]
pub async fn show_model(payload: Json<ShowRequest>, state: &State<ExtensionBridge>) -> AppResult<Json<ShowResponse>> {
    let req = payload.into_inner();
    let _verbose = req.verbose.unwrap_or(false);

    let sign_in_present = request_gemini_sign_in_presence(state).await.ok();
    let input_context_length = context_length_for_sign_in(sign_in_present);

    let entry = gemini_catalog_entry(input_context_length);
    if req.model != entry.tag.model && req.model != entry.tag.name {
        bail!("model not found");
    }

    Ok(Json(ShowResponse {
        modelfile: entry.modelfile,
        parameters: entry.parameters,
        template: entry.template,
        details: entry.tag.details,
        capabilities: entry.capabilities,
        model_info: entry.model_info,
    }))
}
